local DrRayLibrary = loadstring(game:HttpGet("https://raw.githubusercontent.com/Legityt252/Kk/refs/heads/main/DrRay.lua"))()
local window = DrRayLibrary:Load("CatHub", "Default")
local tab = DrRayLibrary.newTab("🥵Antlagg🥵", "ImageIdHere")
tab.newButton("🙃no Textura🙃", "ByLegityt", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Legityt252/Kk/refs/heads/main/antlagv2.lua"))()
end)
tab.newButton("🤑Antlagg🤑", "ByLegityt", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Legityt252/Kk/refs/heads/main/antlag.lua"))()
end)
local tab = DrRayLibrary.newTab("🫢blox fruit🫢", "ImageIdHere")
tab.newButton("💵kaitun💵", "ByLegityt", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Legityt252/Kk/refs/heads/main/cdk.lua"))()
end)
tab.newButton("😶‍🌫️AnnieCrack😶‍🌫️", "ByLegityt", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Legityt252/Kk/refs/heads/main/anniev2.lua"))()
end)
tab.newButton("😝AutoBount😝", "ByLegityt", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Legityt252/Kk/refs/heads/main/autobountv2.lua"))()
end)
tab.newButton("🤪Azure🤪", "ByLegityt", function()
    loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/3b2169cf53bc6104dabe8e19562e5cc2.lua"))()
end)
tab.newButton("🥰Oldbf🥰", "ByLegityt", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Legityt252/Kk/refs/heads/main/ofdbf.lua"))()
end)
tab.newButton("😍Koatta😍", "ByLegityt", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/KOBENFF/sdfd/refs/heads/main/Koatta.txt"))()
end)
tab.newButton("😚FreeScript😚", "ByLegityt", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/TrashLua/BloxFruits/main/FreeScripts.lua"))()
end)
tab.newButton("😄Min Gaming😄", "ByLegityt", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Legityt252/Tiktok-fake-D/refs/heads/main/min%20gamenig.lua"))()
end)
tab.newButton("😇Xete😇r", "ByLegityt", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/LuaCrack/Loader/main/Xeter.lua"))()
end)
tab.newButton("🙂Damon🙂", "ByLegityt", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/daucobonhi/seagame/main/Damonvip.lua"))()
end)
local tab = DrRayLibrary.newTab("👉Scripts👈", "ImageIdHere")
tab.newButton("@#🇧🇷FeTool🇧🇷#@", "ByLegityt", function()

end)
tab.newButton("😄infiniteyield😄", "ByLegityt", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()
end)
tab.newButton("🤩GhostHub🤩", "ByLegityt", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Legityt252/02/refs/heads/main/GhostHub.txt"))()
end)
tab.newButton("#☺️@noclip@😊#", "ByLegityt", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Legityt252/Djdjjdn/refs/heads/main/noclip.txt",true))()
end)
tab.newButton("🫡FeTroll🫡", "ByLegityt", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Legityt252/02/refs/heads/main/FE%20Trolling%20GUI.lua"))()
end)
tab.newButton("😁aimbot😁", "ByLegityt", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Legityt252/Painel-1/refs/heads/main/slime.txt"))()
end)
tab.newButton("🤪Hitbox🤪", "ByLegityt", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Legityt252/Painel-1/refs/heads/main/Hitbox%20univesal.txt"))()
end)
tab.newButton("#🤪@maretao@🤪#", "ByLegityt", function()

end)
tab.newButton("#🤪@esp@🤪#", "ByLegityt", function()
loadstring(game:HttpGet("https://pastebin.com/raw/AXpJyQ7A",true))()
end)
tab.newButton("#🤪@noclip@🤪#", "ByLegityt", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Legityt252/Djdjjdn/refs/heads/main/noclip.txt",true))()
end)
tab.newButton("#🇧🇷@brookhaven🇧🇷@#", "ByLegityt", function()

end)
tab.newButton("🤐redhubz🤐", "ByLegityt", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/REDzHUB/REDzHUB/main/REDzHUB"))()
end)
tab.newButton("😛sanderhub😛", "ByLegityt", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Legityt252/Kk/refs/heads/main/sanderXNewV2.65.lua"))()
end)